name: Build and test Backend

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Backend
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
        
    - name: Build with Gradle
      run: ./gradlew build
